### ISSUE TITLE
Dépassement de capacité lors d'une affectation dans la procédure bEstValeurImmediate 

### ISSUE THREAD

**Issue by GBEXP** [maitrebitcoin/wd-assembly#3]
L'audit dynamique effectuer par WINDEV durant l'exécution détecte un dépassement de capacité lors d'une affectation. 
**Ligne 26 de la procédure globale bEstValeurImmediate.**

L'affectation suivant tente de placer une valeur négative dans un entier non signé :
**valeur_OUT = Val(s)** 

![wdassembly](https://user-images.githubusercontent.com/57711944/71068953-0f9d9880-2178-11ea-870e-6fb7ec5db552.JPG)

**Comment by maitrebitcoin** [comment]
Merci pour ce retour @GBEXP .
Le warning est un peu abusif ici : le code binaire généré est correct. La représentation mémoire de -3 est OK 
Je vais quand même regarder pour l'éliminer.

**Comment by maitrebitcoin** [comment]
corrigé
